name: First Workflow
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Date
      id: set_date
      run: |
        $datetime = Get-Date -Format 'yyyy-MM-dd-HH-mm-ss'
        echo "$datetime"
        echo DATETIME=${{datetime}} >> $GITHUB_ENV

    - name: Display Date and Time - datetime_env
      run: |
        echo "Current Date and Time: ${{ env.DATETIME }}"

    - name: Create Images Directory
      run: |
        mkdir -p "./${{ github.sha }}_${{ env.DATETIME }}_files"

    - name: Run JAR File and Save Output
      run: |
        echo "Original content" > "./${{ github.sha }}_${{ env.DATETIME }}_files/output_.csv"

    - name: Modify Output File
      run: |
        echo "Modified content" > "./${{ github.sha }}_${{ env.DATETIME }}_files/modified_output.csv"

    - name: Third Output File
      run: |
        echo "Third content" > "./${{ github.sha }}_${{ env.DATETIME }}_files/third_output.csv"

    - name: Fourth Output File
      run: |
        echo "blob content" > "./${{ github.sha }}_${{ env.DATETIME }}_files/fourth_output.blob"

    - name: Upload original Output Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }}_${{ env.DATETIME }}_files
        path: ./${{ github.sha }}_${{ env.DATETIME }}_files