name: First Workflow
on: push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Get Code
        run: actions/checkout@v3
      - name: Print goodbye
        run: echo "Done - bye!"