name: First Workflow
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Get current date
      id: datetime
      run: |
        $env:DATETIME = Get-Date -Format "yyyy-MM-ddTHH-mm-ss"
        echo "DATETIME=$env:DATETIME" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Create Images Directory
      run: |
        $DATETIME = $env:DATETIME
        mkdir -p "./${{github.sha}}_${{DATETIME}}_files"

    - name: Run JAR File and Save Output
      run: |
        $DATETIME = $env:DATETIME
        echo "Original content" > "./${{github.sha}}_${{DATETIME}}_files/output_.csv"

    - name: Modify Output File
      run: |
        $DATETIME = $env:DATETIME
        echo "Modified content" > "./${{github.sha}}_${{DATETIME}}_files/modified_output.csv"

    - name: Third Output File
      run: |
        $DATETIME = $env:DATETIME
        echo "Third content" > "./${{github.sha}}_${{DATETIME}}_files/third_output.csv"

    - name: Fourth Output File
      run: |
        $DATETIME = $env:DATETIME
        echo "blob content" > "./${{github.sha}}_${{DATETIME}}_files/fourth_output.blob"

    - name: Upload original Output Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "${{github.sha}}_${{DATETIME}}_files"
        path: "./${{github.sha}}_${{DATETIME}}_files"



#name: First Workflow
#on:
#  push:
#  workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: self-hosted
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Get current date
#      id: datetime
##      run: |
##        $env:DATETIME = Get-Date -Format "yyyy-MM-ddTHH-mm-ss"
##        echo "DATETIME=$env:DATETIME" >> $GITHUB_ENV
#      run: |
#        $DATETIME = Get-Date -Format "yyyy-MM-ddTHH-mm-ss"
#        echo "DATETIME=$env:DATETIME" | Out-File -FilePath $env:GITHUB_ENV -Append




#
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-package: jre
#        java-version: '17'
#
#    - name: Check Java Version
#      run: |
#        java -version
#
#    - name: Create Images Directory
#      run: |
#        $DATETIME = $env:DATETIME
#        mkdir -p "./${{ github.sha }}_${{DATETIME}}_files"
#
#    - name: Run JAR File and Save Output
#      run: |
#        $DATETIME = $env:DATETIME
#        echo "Original content" > "./${{ github.sha }}_${{DATETIME}}_files/output_.csv"
#
#    - name: Modify Output File
#      run: |
#        $DATETIME = $env:DATETIME
#        echo "Modified content" > "./${{ github.sha }}_${{DATETIME}}_files/modified_output.csv"
#
#    - name: Third Output File
#      run: |
#        $DATETIME = $env:DATETIME
#        echo "Third content" > "./${{ github.sha }}_${{DATETIME}}_files/third_output.csv"
#
#    - name: Fourth Output File
#      run: |
#        $DATETIME = $env:DATETIME
#        echo "blob content" > "./${{ github.sha }}_${{DATETIME}}_files/fourth_output.blob"
#
#    - name: Upload original Output Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: "${{ github.sha }}_${{env:DATETIME}}_files"
#        path: "./${{ github.sha }}_${{env:DATETIME}}_files"


#
#
#name: Second Workflow
#on: [push, workflow_dispatch]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-package: jre
#        java-version: '17'
#
#    - name: Check Java Version
#      run: |
#        java -version
#
#
#  download_original:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-package: jre
#        java-version: '17'
#
#    - name: Check Java Version
#      run: |
#        java -version
#
#
#    - name: Run JAR File and Save Output
#      run: |
#        echo "Original content" > output.csv
#
#    - name: Upload original Output Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: output.csv
#        path: output.csv
#
#
#  download_modified:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-package: jre
#        java-version: '17'
#
#    - name: Check Java Version
#      run: |
#        java -version
#
#
#    - name: Modify Output File
#      run: |
#        echo "Modified content" > modified_output.csv
#
#    - name: Upload Modified Output Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: modified_output.csv
#        path: modified_output.csv
#
#
#  download_third:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-package: jre
#        java-version: '17'
#
#    - name: Check Java Version
#      run: |
#        java -version
#
#
#    - name: Third Output File
#      run: |
#        echo "Third content" > third_output.csv
#
#    - name: Upload Third Output Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: third_output.csv
#        path: third_output.csv
#
#
#  download_forth:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-package: jre
#        java-version: '17'
#
#    - name: Check Java Version
#      run: |
#        java -version
#
#
#    - name: Forth Output File
#      run: |
#        echo "blob content" > forth_output.blob
#
#    - name: Upload forth Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: forth_output.blob
#        path: forth_output.blob
#




#name: Third Workflow
#on: [push, workflow_dispatch]
#
#jobs:
#  build:
#    runs-on: self-hosted
#
#    strategy:
#      matrix:
#        file:
#          - output.csv
#          - modified_output.csv
#          - third_output.csv
#          - forth_output.blob
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-package: jre
#        java-version: '17'
#
#    - name: Check Java Version
#      run: |
#        java -version
#
#    - name: Run JAR File and Save Output
#      run: |
#        echo "Original content" > ${{ matrix.file }}
#
#    - name: Upload Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: ${{ matrix.file }}
#        path: ${{ matrix.file }}
#
#    - name: Download Artifact
#      uses: actions/download-artifact@v3
#      with:
#        name: ${{ matrix.file }}