name: First Workflow
on: [push,workflow_dispatch]
jobs:
  first-job:
    runs-on: self-hosted

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Create text file
        run: |
          current_datetime=$(Get-Date -Format "yyyyMMddHHmmss")
          filename="${current_datetime}.txt"
          echo "This is the content of the file" > "$filename"
          mv "$filename" $GITHUB_WORKSPACE/
