name: First Workflow
on: [push,workflow_dispatch]
jobs:
  first-job:
    runs-on: self-hosted

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Create text file
        run: |
          echo "This is the content of the file fdsfsdfsdfsdfsdfdsf" > file4.txt
          mv file4.txt $GITHUB_WORKSPACE/

      - name: Archive code
        uses: actions/upload-artifact@v3
        with:
          name: code-report
          path: ../file4.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
